name: 🐞 Achei um Bug!
description: Reporte um bug aqui
title: "[BUG]: "
labels: ["bug"]
assignees: ["alessfm"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por informar sobre o bug 🤗
        Por favor, antes de relatar, olhe as *issues* para ver se esse bug já foi reportado 😃
        
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: O que aconteceu? O que deveria ter acontecido?
      placeholder: |
        Forneça logs, screenshots, o máximo de informação que ajude
    validations:
      required: true
      
  - type: textarea
    id: como-reproduzir
    attributes:
      label: Como reproduzir?
      description: O que dever ser feito para o bug acontecer?
      placeholder: |
        1. Vá para '...'
        2. Clique no '...'
        3. Veja o erro '...'
    validations:
      required: true

  - type: textarea
    id: informacao-adicional
    attributes:
      label: Informação adicional
      description: |
        Qualquer informação que não se encaixa na descrição, mas que é útil e deve ser informada.
