name: 👀 Quero mudanças!
description: Solicite uma melhoria, adição...
title: "[FEAT]: "
labels: ["enhancement"]
assignees: ["alessfm"]
body:
  - type: markdown
    attributes:
      value: Por favor, antes de relatar, olhe as *issues* para ver se já foi solicitada 😃

  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: O que gostaria?
      placeholder: Forneça logs, screenshots, o máximo de informação que ajude
    validations:
      required: true

  - type: textarea
    id: informacao-adicional
    attributes:
      label: Informação adicional
      description: Qualquer informação que não se encaixa na descrição, mas que é útil e deve ser informada.
      placeholder: Digite aqui...
