name: ✨Requerimento de Mudanças
description: Peça uma mudança, adição, melhoria...
labels: ["enhancement"]
assignees: ["alessfm"]
title: "[FEAT]: "
body:
  - type: markdown
    attributes:
      value: |
        Por favor, antes de relatar, olhe as *issues* para ver se essa requisição já foi solicitada 😃
  
  - type: textarea
    id: descricao
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true
      
  - type: textarea
    id: informacao-adicional
    attributes:
      label: Informação adicional
      description: Qualquer informação que não se encaixa na descrição, mas que é útil e deve ser informada.
